version: '3.5'

services:

  dj-mongo:
    image: mongo:3.4.21
    container_name: dj-mongo-srv
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - dj_mongo_data:/data/db
    networks:
      - dj-network

  # http://localhost:8081
  dj-mongo-express:
    image: mongo-express:0.49.0
    container_name: dj-mongo-express-srv
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - dj-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: dj-mongo-srv
    networks:
      - dj-network

networks:
  dj-network:
    name: dj-network


volumes:
  dj_mongo_data:
    name: dj_mongo_data