version: '3.6'

services:

  # http://localhost:8080
  rabbitmq:
    image: rabbitmq:3.7.17-management
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    hostname: rabbitmq-srv
    container_name: rabbitmq-srv
    ports:
      - 5672:5672
      - 8080:15672
    networks:
      - dj-network

networks:
  dj-network:
    name: dj-network