package com.zalizniak.awsdynamodbdao;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@ToString
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode()
@DynamoDBTable(tableName = "dj.dynamodb.users")
public class User {

    @EqualsAndHashCode.Include
    private String id;

    @EqualsAndHashCode.Exclude
    private String firstName;

    @EqualsAndHashCode.Exclude
    private String lastName;

    @DynamoDBHashKey(attributeName = "user_id")
    // @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "first_name")
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute(attributeName = "last_name")
    public String getLastName() {
        return lastName;
    }

}