package com.zalizniak.awsdynamodbdao;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@ToString
@Setter
@NoArgsConstructor
@EqualsAndHashCode()
@DynamoDBTable(tableName = "dj.dynamodb.users")
public class User {

    @EqualsAndHashCode.Include
    private String userId;

    @EqualsAndHashCode.Exclude
    private String firstName;

    @EqualsAndHashCode.Exclude
    private String lastName;

    @EqualsAndHashCode.Exclude
    private Integer userAge;

    @EqualsAndHashCode.Exclude
    private Long version;

    public User(String userId, String firstName, String lastName, Integer age) {
        this.userId = userId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.userAge = age;
    }

    @DynamoDBHashKey(attributeName = "user_id")
    // @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return userId;
    }

    @DynamoDBAttribute(attributeName = "first_name")
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute(attributeName = "last_name")
    public String getLastName() {
        return lastName;
    }

    @DynamoDBAttribute(attributeName = "user_age")
    public Integer getUserAge() {
        return userAge;
    }

    // https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html
    @DynamoDBVersionAttribute(attributeName = "version")
    public Long getVersion() {
        return version;
    }
}